"""Generate manuscript tables from outputs/ artifacts.

Every table is built directly from a source CSV/JSON so the numbers match exactly.
Each output file carries a header comment naming its source for traceability.

Usage:
    python src/generate_tables.py
Outputs:
    outputs/tables/table3_kimore_summary.md
    outputs/tables/table4_per_exercise_spearman.md
    outputs/tables/table5_pairwise_sample_level.md
    outputs/tables/table6_irds_reliability.md
    outputs/tables/table_protocol_inflation.md
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

OUT_DIR = Path("outputs/tables")
OUT_DIR.mkdir(parents=True, exist_ok=True)


def _df_to_md(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub-flavoured Markdown table (no tabulate dep)."""
    cols = [str(c) for c in df.columns]
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    rows = []
    for _, row in df.iterrows():
        cells = ["" if pd.isna(v) else str(v) for v in row.tolist()]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([header, sep, *rows])


def _write(name: str, source: str, title: str, body: str) -> None:
    path = OUT_DIR / name
    text = f"<!-- {title}\n     Source: {source}\n     Auto-generated by src/generate_tables.py -->\n\n{body}\n"
    path.write_text(text, encoding="utf-8")
    print(f"  -> {path}")


def table3_kimore_summary() -> None:
    src = "outputs/sample_stats/per_exercise_spearman.csv"
    df = pd.read_csv(src)
    cols = ["Model", "Protocol", "Mean rho", "Mean rho 95% CI"]
    out = df[[c for c in cols if c in df.columns]].copy()
    body = _df_to_md(out)
    _write("table3_kimore_summary.md", src,
           "Table 3: KIMORE pooled-OOF mean Spearman rho with bootstrap 95% CI", body)


def table4_per_exercise_spearman() -> None:
    src = "outputs/sample_stats/per_exercise_spearman.csv"
    df = pd.read_csv(src)
    body = _df_to_md(df)
    _write("table4_per_exercise_spearman.md", src,
           "Table 4: Per-exercise Spearman rho (Stratified LOSO)", body)


def table5_pairwise_sample_level() -> None:
    src = "outputs/sample_stats/pairwise_sample_level.csv"
    df = pd.read_csv(src)
    body = _df_to_md(df)
    _write("table5_pairwise_sample_level.md", src,
           "Table 5: Pairwise sample-level tests (N=380 Wilcoxon, Holm-Bonferroni)", body)


def table6_irds_reliability() -> None:
    src = "outputs/irds_eval/irds_reliability.csv"
    df = pd.read_csv(src)
    # Keep the deployment-relevant columns including pred_SD and degenerate.
    cols = ["model", "ICC_testretest", "Kendall_W", "mean_cross_ex_rho",
            "mean_F_between_subj", "pred_SD", "degenerate"]
    out = df[[c for c in cols if c in df.columns]].copy()
    body = _df_to_md(out)
    _write("table6_irds_reliability.md", src,
           "Table 6: IRDS zero-shot reliability (with pred_SD and degenerate flag)", body)


def table_protocol_inflation() -> None:
    src = "outputs/novelty/protocol_decomposition.json"
    with open(src, encoding="utf-8") as fh:
        d = json.load(fh)
    grid = d["grid"]
    rows = []
    for key, cell in grid.items():
        rows.append({
            "Cell": key,
            "Label": cell["label"],
            "Mean rho": round(cell["mean_rho"], 4),
            "SD rho": round(cell["sd_rho"], 4),
        })
    body = _df_to_md(pd.DataFrame(rows))
    le = d["main_effect_subject_leakage"]
    le_ci = d["main_effect_subject_leakage_ci95"]
    st = d["main_effect_clinical_stratification"]
    st_ci = d["main_effect_clinical_stratification_ci95"]
    body += (
        "\n\n**Main effects (vs Stratified LOSO reference):**\n\n"
        f"- Subject-leakage: {le:+.4f} rho "
        f"(95% CI [{le_ci[0]:.4f}, {le_ci[1]:.4f}])\n"
        f"- Clinical-stratification: {st:+.4f} rho "
        f"(95% CI [{st_ci[0]:.4f}, {st_ci[1]:.4f}])\n"
        f"- Interaction: {d['interaction']:+.4f}; "
        f"total inflation vs LOSO: {d['total_inflation_vs_loso']:+.4f}\n"
    )
    _write("table_protocol_inflation.md", src,
           "Protocol-inflation 2x2 decomposition", body)


def main() -> None:
    print("Generating tables...")
    for fn in [table3_kimore_summary, table4_per_exercise_spearman,
               table5_pairwise_sample_level, table6_irds_reliability,
               table_protocol_inflation]:
        try:
            fn()
        except Exception as e:  # noqa: BLE001
            print(f"  [ERROR] {fn.__name__}: {e}")
    print(f"Done. Tables in {OUT_DIR}/")


if __name__ == "__main__":
    main()
